### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jjj-guo** [AbdullahO/mSSA#4]
File "D:\PycharmProjects\mSSA-master\mssa\src\tsUtils.py", line 116, in pInverseMatrixFromSVD
    s = s - soft_threshold
TypeError: unsupported operand type(s) for -: 'list' and 'int'

I don't kown how to solve it.

**Comment by AbdullahO** [comment]
Thanks jjj-guo for pointing this bug out.

I believe that your problem is due to a small bug in the default was one of the algorithm parameters is set (rank). I just pushed a the fix. If that did not fix your issue, please let me know.  

Also, if the issue is not fixed, could you kindly attach a snippet of your code so I can pinpoint where the problem is? 

Thank you.

**Comment by jjj-guo** [comment]
It is a great honor to receive your reply.This problem only occurs when I input a specific data set. If possible, I would like to request your email address, and I will send you that CSV file.

**Comment by jjj-guo** [comment]
I've been following your example, but I still have a problem

**Comment by AbdullahO** [comment]
Thanks jjj-guo, can you add the example (code and data) in a new GitHub repo of your own, and I'll take a look at it that way.

Thanks again for reporting this issue.
